#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to listen on port 80 and return "Hello World!"
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;

    index index.html;

    server_name _;

    location / {
        default_type text/html;
        return 200 'Hello World!';
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        log_not_found off;
        access_log off;
    }

    error_page 404 /index.html;

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}" > /etc/nginx/sites-available/default

# Create a symbolic link to enable the site
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled

# Remove the default Nginx welcome page
rm -rf /var/www/html/*

# Restart Nginx
service nginx restart
