#!/usr/bin/env bash

# Update packages
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create the custom 404 page
echo "<html><body><h1>Ceci n'est pas une page</h1></body></html>" | sudo tee /var/www/html/404.html

# Create a new Nginx configuration file
echo "server {
 listen 80 default_server;
 listen [::]:80 default_server;

 root /var/www/html;
 index index.html;

 location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
 }

 error_page 404 /404.html;
 location = /404.html {
    root /var/www/html;
    internal;
 }
}" | sudo tee /etc/nginx/sites-available/default

# Enable the new configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Restart Nginx
sudo service nginx restart
